version: "2"

services:
  base:
    image: node:16
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i

  install-ci:
    extends:
      service: base
    command: npm ci

  npmlist:
    extends:
      service: base
    command: npm list --depth=0

  test:
    extends:
      service: base
    command: npm run test

  test-watch:
    extends:
      service: base
    command: npm run test-watch

  build:
    extends:
      service: base
    command: npm run build
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org

  build_staging:
    extends:
      service: base
    command: npm run build-staging
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org

  create-bundles:
    extends:
      service: base
    command: npm run create-bundles

volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
