version: '2'

services:
  base:
    image: node:12
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
  
  install:
    extends:
      service: base
    command: npm i
  
  build:
    extends:
      service: base
    command: npm run build
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org
    
  create-bundles:
    extends:
      service: base
    command: npm run create-bundles

volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
