version: "4"

services:
  documentcloud_frontend:
    image: node:18
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run watch
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org

  documentcloud_frontend_app:
    image: node:18
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run dev-app
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org

  documentcloud_frontend_embed:
    image: node:18
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run dev-embed
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org

  documentcloud_frontend_build:
    image: node:18
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run build-serve
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org

  documentcloud_frontend_analyze:
    image: node:18
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run build-analyze
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org

volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
