version: "3"

services:
  base:
    image: node:20
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=production

  install:
    extends:
      service: base
    command: npm ci && npm audit fix
    environment:
      DOCKER: true
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # todo: solve local certificate chain issues
      NODE_ENV: development
      PUPPETEER_SKIP_DOWNLOAD: true

  npmlist:
    extends:
      service: base
    command: npm list --depth=0

  test:
    extends:
      service: base
    command: npm run test

  test-watch:
    extends:
      service: base
    command: npm run test-watch

  build:
    extends:
      service: base
    command: npm run build
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org

  # TODO: Specify that base must be running first.
  browser-test:
    build:
      dockerfile: browser-test.Dockerfile
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org
    environment:
      - NODE_ENV=test
    command: ./browser-test-all.sh

volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
