version: '3'

services:
  documentcloud_frontend:
    image: node:12
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run serve
    networks:
      default:
        aliases:
          - www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - www.dev.documentcloud.org
  cypress:
    image: "cypress/included:3.6.1"
    depends_on:
      - documentcloud_frontend
    environment:
      - CYPRESS_baseUrl=http://documentcloud_frontend:80
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
  
volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
