services:
  documentcloud_frontend:
    image: node:22
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run dev
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org
    environment:
      DOCKER: true
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # todo: solve local certificate chain issues
      NODE_ENV: development

  preview:
    image: node:22
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run preview
    networks:
      default:
        aliases:
          - internal.www.dev.documentcloud.org
      squarelet_default:
        aliases:
          - internal.www.dev.documentcloud.org
    environment:
      DOCKER: true
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # todo: solve local certificate chain issues
      NODE_ENV: development

volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true
