version: '3'

services:
  documentcloud_frontend:
    image: node:12
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    ports:
      - "80:80"
    command: npm run serve
    networks:
      default:
        aliases:
          - dev.documentcloud.org
      squarelet_default:
        aliases:
          - dev.documentcloud.org
  
volumes:
  nodemodules:
    external: true

networks:
  squarelet_default:
    external: true