// this route was sometimes generated by old embeds and should redirect

import { redirect } from "@sveltejs/kit";
import { EMBED_URL } from "@/config/config.js";

export function load({ params }) {
  const { id, note_id } = params;

  // the embed route can handle errors
  const url = new URL(
    `/documents/${id}/annotations/${note_id}/?embed=1`,
    EMBED_URL,
  );

  return redirect(302, url);
}
