# https://www.netlifycms.org/docs/add-to-your-site/#backend
backend:
  name: git-gateway
  branch: staging # Branch to update (optional; defaults to master)

# https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
publish_mode: editorial_workflow

# Media and public folders
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections
collections:
  - name: "help" # Used in routes, e.g., /admin/collections/help
    label: "Help" # Used in the UI
    folder: "src/help/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "help" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
