# https://www.netlifycms.org/docs/add-to-your-site/#backend
backend:
  name: github
  repo: muckrock/documentcloud-frontend
  site_domain: beta.documentcloud.org
  branch: master # Branch to update (optional; defaults to master)

# https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
publish_mode: editorial_workflow

# Media and public folders
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/docs
    label: "Doc" # Used in the UI
    folder: "docs/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "docs" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight", name: "weight", widget: "string", default: "1" }
      - { label: "Body", name: "body", widget: "markdown" }
