# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  pull_request:
    paths:
      - "src/**"
      - "static/**"
      - "!src/**/*.ts.snap"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches: [main]
    paths:
      - "src/**"
      - "static/**"
      - "!src/**/*.ts.snap"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history
          ref: ${{ github.event.pull_request.head.ref }} # Tell the checkout which commit hash to reference
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - run: npm run sync
      - run: npm run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          # onlyChanged: true
          # externals: |
          #  - 'public/**'
