name: Coverage Report

on:
  pull_request:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          test-script: npm run test-coverage
