name: Playwright Tests

on:
  pull_request:
    branches: [master]

env:
  URL: "https://deploy-preview-${{ github.event.number }}.muckcloud.com"

jobs:
  wait:
    runs-on: ubuntu-latest

    steps:
      - uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: ${{ env.URL }}
          responseCode: "200"
          timeout: 120000
          interval: 3000

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: wait

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
