name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci
      - run: npm run sync
      - run: npm run build
        env:
          NODE_ENV: production
      - run: npm run test:coverage
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci
      - run: npm run sync
      - run: npm run build
        env:
          NODE_ENV: production
      - run: npm run check
